// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantManagement.Api.Models;

public partial class TblMenu
{
    public Guid MnuId { get; set; }

    public string MnuName { get; set; }

    public decimal MnuPrice { get; set; }

    public string MnuStatus { get; set; }

    public string MnuImage { get; set; }

    public string MnuDescription { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<TblOrderDetail> TblOrderDetails { get; set; } = new List<TblOrderDetail>();
}