// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using RestaurantManagement.Core.Enums;
using System;
using System.Collections.Generic;

namespace RestaurantManagement.Api.Models;

public partial class TblReservation
{
    public Guid ResId { get; set; }

    public Guid CusId { get; set; }

    public Guid TbiId { get; set; }

    public DateTime ResDate { get; set; }

    public TimeOnly ResTime { get; set; }

    public int ResNumber { get; set; }

    public ReservationStatus ResStatus { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual TblCustomer Cus { get; set; }

    public virtual TblTableInfo Tbi { get; set; }

    public virtual ICollection<TblOrderInfo> TblOrderInfos { get; set; } = new List<TblOrderInfo>();

    // Thuộc tính tính toán thời gian rời đi
    public DateTime DepartureTime => ResDate.Add(ResTime.ToTimeSpan());
}