// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantManagement.Api.Models;

public partial class TblUserAccount
{
    public Guid UacId { get; set; }

    public string UacEmail { get; set; }

    public string UacPassword { get; set; }

    public string UacRole { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<TblStaff> TblStaffs { get; set; } = new List<TblStaff>();
}