version: "1.0"
services:
  test:
    container_name: test
    image: restaurant-management:0.0.1
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5075
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5075:5075
    restart: always
    networks:
      - k1-network
networks:
  k1-network: